### ISSUE TITLE
Use ocamllex for retrieval of variables from SQL

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [issuu/ppx_mysql#10]
It is very easy to integrate the built-in `ocamllex` in `dune` projects (like done e.g. in sure-deploy) and that would give us a lexing function for free (and remove the dependency on `re` for better or worse). The current lexing function works but why maintain code when using built-in tools would do the job in a more readable way.

**Comment by darioteixeira** [comment]
PR #13 fixes this.

**Comment by Leonidas-from-XIV** [comment]
You could add `Fixes #13` in one of the commit messages long description, then merging it to master would automatically close this issue. I think it is a neat bit of automation that Github offers.
