### ISSUE TITLE
Subpackages for Mysql_syntax for the MySQL library and maybe others

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [issuu/ppx_mysql#8]
I think there should be an implementation of the `Mysql_syntax` module signature outlined in #7 for at least the `mysql` library, which would most likely be a subpackage of `ppx_mysql` and would have an OPAM dependency on `mysql`.

A possible stretch goal would be to implement this also with the `mariadb` library or the `mysql_protocol` library, to see whether the signature can be implemented in a reasonable way or whether it is too much tied to the way `mysql` runs things.

**Comment by darioteixeira** [comment]
Implemented by PR #18.
